### ISSUE TITLE
Mac app is packaged incorrectly

### ISSUE THREAD

**Issue by deseven** [aleksijuvani/rgo19#1]
Hi. I downloaded macos release from [this page](https://r-ven.itch.io/rgo19), but it doesn't work.

You have files placed in app's root, that's wrong. Typical bundle structure should look like this:
![](https://doc.qt.io/archives/qq/qq09-demo-icon.png)

Where `Contents/MacOS/demo` is the main executable and `Contents/Info.plist` is the main property list with all application settings (including icon and executable name).

**Comment by deseven** [comment]
So in your case the correct structure would be:
```
rgo19.app
└── Contents
    ├── Info.plist
    ├── MacOS
    │   └── rgo19
    └── Resources
        ├── *.rtex
        ├── *.rmdl
        └── *.rscn
```
Can't test it myself because there are no resources in this repo.

**Comment by aleksijuvani** [comment]
Thank you for letting me know! I can't seem to be able to reproduce the issue. What is the exact error message? Which version of macOS are you running? The game is using `pathForResource:ofType:` for locating resources, so you might be able to test this by moving the resources around inside the bundle, and it should be able to locate them without needing a recompile. Does the issue persist if you install the game using the itch.io client instead?

**Comment by deseven** [comment]
Sorry, after some digging i found out the issue - you app requires macOS 10.15 which introduced a support for iOS apps and their bundle layout.

As you can see [here](https://developer.apple.com/library/archive/documentation/CoreFoundation/Conceptual/CFBundles/BundleTypes/BundleTypes.html) (chapters "Anatomy of an iOS Application Bundle" and "Anatomy of a macOS Application Bundle") bundle structures are pretty different and your app follows the iOS one (which is totally fine on macOS 10.15!).

I'm still on 10.14 and trying to start your game gives me some confusing errors like `LSOpenURLsWithRole() failed for the application /Volumes/FAST/Applications/rgo19.app with error -10825.`.

So there is no real problem, just a compatibility issue, in any case you may want to add 10.15 and/or Metal 3.0 to system requirements and that's it.

**Comment by aleksijuvani** [comment]
I see! I've added macOS 10.15 to the system requirements. Ideally I'd also support 10.14, but testing on two different macOS versions would be a bunch of additional work for what is essentially a prototype/game jam submission.
